package XXLChess;


import processing.core.PApplet;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import processing.core.PImage;
import processing.data.JSONObject;
import processing.data.JSONArray;
import processing.core.PFont;
import processing.event.MouseEvent;

import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;

import java.awt.Font;
import java.io.*;
import java.util.*;
import java.lang.Math;

public class AppTest {
    @Test
    //All the code below is just simulating a game that was played by me
    public void setupTest() {
        App a = new App();
        PApplet.runSketch(new String[]{"test game"}, a);
        a.setup();
        a.draw();
        a.key = 'a';
        a.keyPressed();
        a.draw();
        a.keyPressed();
        a.draw();
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        MouseEvent m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 361, 594, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 358, 518, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 411, 71, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 415, 160, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 326, 642, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 647, 309, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 405, 32, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 451, 124, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 653, 307, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 638, 54, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 505, 32, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 545, 110, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 663, 66, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 650, 39, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 596, 73, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 597, 156, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 627, 33, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 578, 28, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 293, 32, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 375, 111, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 588, 19, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 555, 122, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 357, 114, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 563, 119, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 559, 72, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 274, 635, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 364, 498, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 357, 321, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 365, 497, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 357, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 315, 639, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 551, 70, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 459, 128, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 543, 170, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 546, 85, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 546, 154, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 594, 160, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 594, 193, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 554, 172, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 554, 35, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 453, 68, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 454, 164, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 531, 22, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 460, 22, 0, 1);
        a.mousePressed(m);
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        a.key = 'a';
        a.keyPressed();
        a.draw();
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        a.key = 'a';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 361, 594, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 358, 518, 0, 1);
        a.mousePressed(m);
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 361, 594, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 358, 518, 0, 1);
        a.mousePressed(m);
        a.draw();
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        a.key = 'a';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 361, 594, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 358, 518, 0, 1);
        a.mousePressed(m);
        a.drawValidMove();
        a.draw();
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        for(int i = 0; i < 10800; i++){
            a.draw();
        }
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        a.key = 'a';
        a.keyPressed();
        a.draw();
        for(int i = 0; i < 10800; i++){
            a.draw();
        }
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 361, 594, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 358, 518, 0, 1);
        a.mousePressed(m);
        a.draw();
        for(int i = 0; i < 10800; i++){
            a.draw();
        }
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 356, 592, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 359, 499, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 349, 76, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 361, 62, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 383, 62, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 360, 53, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 401, 55, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 418, 193, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 411, 88, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 413, 164, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 315, 639, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 661, 298, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 465, 72, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 463, 162, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 283, 69, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 264, 172, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 591, 20, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 637, 170, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 603, 31, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 648, 160, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 591, 29, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 648, 112, 0, 1);
        a.mousePressed(m);
        a.draw();
        for(int i = 0; i < 600; i++){
            a.draw();
        }
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 321, 605, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 320, 517, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 270, 65, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 269, 176, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 369, 631, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 305, 596, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 317, 5, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 122, 204, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 310, 576, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 255, 536, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 126, 227, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 205, 222, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 254, 558, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 265, 510, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 216, 211, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 278, 218, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 141, 593, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 122, 550, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 267, 506, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 210, 469, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 275, 204, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 143, 218, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 207, 451, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 159, 449, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 119, 221, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 177, 260, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 165, 432, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 180, 375, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 166, 451, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 170, 418, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 167, 446, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 135, 453, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 165, 272, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 199, 304, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 111, 450, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 74, 416, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 201, 315, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 213, 346, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 71, 407, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 30, 410, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 216, 358, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 107, 410, 0, 1);
        a.mousePressed(m);
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 305, 625, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 351, 544, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 295, 28, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 352, 126, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 345, 555, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 355, 284, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 360, 114, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 354, 272, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 269, 597, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 269, 517, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 347, 284, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 360, 404, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 259, 504, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 276, 432, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 291, 68, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 311, 185, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 261, 444, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 266, 406, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 311, 192, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 305, 177, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 309, 218, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 262, 412, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 268, 365, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 303, 211, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 309, 261, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 273, 362, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 283, 296, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 317, 263, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 311, 298, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 270, 305, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 273, 268, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 303, 304, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 305, 342, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 266, 266, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 507, 266, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 309, 356, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 161, 500, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 495, 272, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 649, 403, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 365, 406, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 176, 602, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 263, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 220, 546, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 163, 503, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 201, 545, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 398, 632, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 368, 551, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 221, 546, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 367, 552, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 646, 415, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 644, 64, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 648, 21, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 647, 62, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 167, 588, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 221, 610, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 227, 507, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 167, 603, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 205, 632, 0, 1);
        a.mousePressed(m);
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 301, 633, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 347, 540, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 308, 37, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 353, 117, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 259, 652, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 213, 541, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 263, 37, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 299, 126, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 219, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 260, 486, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 213, 23, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 261, 154, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 166, 600, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 171, 488, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 215, 74, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 209, 76, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 180, 76, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 180, 176, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 123, 639, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 183, 605, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 179, 12, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 131, 113, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 122, 14, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 182, 641, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 129, 563, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 124, 25, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 207, 120, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 83, 626, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 33, 546, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 75, 28, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 162, 78, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 361, 626, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 268, 627, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 352, 12, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 269, 16, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 167, 512, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 170, 469, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 172, 188, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 172, 228, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 167, 442, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 167, 409, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 170, 207, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 170, 259, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 172, 403, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 174, 352, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 169, 277, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 173, 278, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 79, 74, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 71, 132, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 171, 354, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 169, 330, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 92, 130, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 81, 162, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 168, 306, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 169, 276, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 64, 160, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 73, 216, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 151, 266, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 262, 158, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 73, 222, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 75, 261, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 262, 172, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 89, 166, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 75, 248, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 71, 310, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 71, 178, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 111, 105, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 69, 315, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 67, 372, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 116, 122, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 75, 170, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 75, 355, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 73, 184, 0, 1);
        a.mousePressed(m);
        a.draw();
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 35, 608, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 24, 514, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 31, 632, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 28, 84, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 35, 168, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 21, 646, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 21, 554, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 29, 22, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 28, 146, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 11, 25, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 39, 118, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 64, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 111, 568, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 85, 32, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 121, 117, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 71, 598, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 75, 510, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 77, 76, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 70, 170, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 111, 652, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 81, 614, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 123, 28, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 69, 72, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 165, 627, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 201, 558, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 161, 32, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 207, 130, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 204, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 157, 494, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 220, 28, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 167, 154, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 263, 638, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 311, 547, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 260, 5, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 301, 119, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 303, 635, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 269, 534, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 300, 19, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 261, 98, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 365, 642, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 365, 642, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 407, 628, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 366, 551, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 400, 26, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 401, 21, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 366, 22, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 366, 22, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 403, 25, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 361, 117, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 448, 634, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 420, 507, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 461, 16, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 403, 162, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 504, 641, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 460, 545, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 501, 32, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 452, 120, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 501, 592, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 495, 512, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 497, 75, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 501, 171, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 545, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 507, 593, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 549, 34, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 503, 69, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 595, 628, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 557, 553, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 599, 22, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 557, 113, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 364, 642, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 440, 639, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 370, 12, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 441, 26, 0, 1);
        a.mousePressed(m);
        a.draw();
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 639, 601, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 655, 490, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 649, 73, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 645, 156, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 651, 645, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 649, 556, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 636, 24, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 644, 130, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 597, 631, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 545, 552, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 592, 41, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 555, 109, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 597, 585, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 597, 551, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 602, 68, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 596, 110, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 556, 634, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 593, 596, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 551, 28, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 609, 79, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 497, 68, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 490, 630, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 456, 539, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 497, 38, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 469, 114, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 455, 634, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 489, 520, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 457, 31, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 504, 162, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 398, 626, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 354, 541, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 389, 39, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 355, 108, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 317, 642, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 275, 536, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 305, 28, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 264, 121, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 257, 641, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 300, 566, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 263, 40, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 303, 118, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 229, 638, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 263, 494, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 209, 30, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 257, 156, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 171, 625, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 204, 568, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 165, 38, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 203, 120, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 111, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 155, 612, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 155, 612, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 163, 519, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 156, 80, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 163, 168, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 125, 638, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 171, 578, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 121, 32, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 167, 78, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 75, 630, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 100, 563, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 59, 30, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 116, 127, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 365, 628, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 394, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 361, 36, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 316, 18, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 401, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 366, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 325, 16, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 360, 23, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 341, 632, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 299, 638, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 371, 36, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 316, 28, 0, 1);
        a.mousePressed(m);
        a.draw();
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key ='r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 306, 634, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 364, 535, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 311, 30, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 277, 103, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 269, 596, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 271, 496, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 254, 97, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 254, 492, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 373, 544, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 309, 464, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 266, 505, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 311, 462, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 263, 642, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 220, 549, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 298, 441, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 212, 560, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 225, 638, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 262, 495, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 223, 543, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 271, 493, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 167, 625, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 118, 541, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 257, 489, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 256, 625, 0, 1);
        a.mousePressed(m);
        a.key = 'a';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 303, 602, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 307, 514, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 261, 74, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 265, 174, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 303, 16, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 215, 632, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 160, 491, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 318, 29, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 28, 308, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 170, 514, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 214, 364, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 77, 600, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 73, 535, 0, 1);
        a.mousePressed(m);
        a.draw();
        for(int i = 0; i < 600; i++){
            a.draw();
        }
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 309, 22, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 301, 643, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 260, 548, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 269, 50, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 263, 171, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 245, 546, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 265, 147, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 306, 22, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 258, 124, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 261, 153, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 261, 123, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 255, 23, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 305, 124, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 265, 122, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 268, 178, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 319, 128, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 260, 128, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 265, 149, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 272, 113, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 569, 54, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 555, 156, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 251, 116, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 254, 10, 0, 1);
        a.mousePressed(m);
        a.key = 'a';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 309, 22, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 301, 643, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 260, 548, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 269, 50, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 263, 171, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 245, 546, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 265, 147, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 306, 22, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 258, 124, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 261, 153, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 261, 123, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 255, 23, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 305, 124, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 265, 122, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 268, 178, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 319, 128, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 260, 128, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 265, 149, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 272, 113, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 569, 54, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 555, 156, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 251, 116, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 254, 10, 0, 1);
        a.mousePressed(m);
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 633, 618, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 635, 506, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 629, 72, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 646, 181, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 647, 638, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 649, 550, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 647, 28, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 653, 122, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 25, 595, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 21, 486, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 27, 71, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 27, 170, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 28, 632, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 16, 560, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 29, 14, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 35, 114, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 420, 644, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 447, 551, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 292, 32, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 265, 106, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 378, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 397, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 338, 40, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 313, 34, 0, 1);
        a.mousePressed(m);
        a.draw();
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        a.key = 'a';
        a.keyPressed();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 633, 618, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 635, 506, 0, 1);
        a.mousePressed(m);
        a.player2Time = 0;
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 314, 592, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 297, 494, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 310, 70, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 310, 70, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 256, 71, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 259, 171, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 412, 634, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 438, 565, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 325, 12, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 27, 315, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 361, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 405, 640, 0, 1);
        a.mousePressed(m);
        a.draw();
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        a.autoMove();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 396, 630, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 437, 570, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 310, 30, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 265, 116, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 456, 642, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 498, 489, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 281, 29, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 298, 122, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 367, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 367, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 496, 643, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 550, 543, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 208, 10, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 261, 168, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 554, 637, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 621, 611, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 615, 609, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 597, 509, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 143, 25, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 166, 82, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 166, 82, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 166, 128, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 554, 651, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 587, 612, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 175, 40, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 216, 111, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 600, 646, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 641, 551, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 123, 31, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 160, 64, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 365, 638, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 441, 638, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 64, 29, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 106, 108, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 255, 591, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 261, 530, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 355, 12, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 285, 13, 0, 1);
        a.mousePressed(m);
        a.draw();
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 318, 642, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 377, 526, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 316, 628, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 359, 565, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 423, 30, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 453, 126, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 265, 641, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 313, 546, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 451, 30, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 498, 167, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 225, 638, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 252, 522, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 512, 18, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 549, 104, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 166, 645, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 229, 551, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 514, 66, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 508, 127, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 158, 607, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 163, 554, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 559, 9, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 506, 78, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 115, 646, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 167, 604, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 593, 22, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 633, 111, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 78, 632, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 115, 562, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 360, 36, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 446, 20, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 360, 635, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 273, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 321, 605, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 321, 516, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 256, 75, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 262, 176, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 303, 640, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 259, 536, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 303, 30, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 33, 312, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 312, 494, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 313, 475, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 31, 317, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 166, 458, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 264, 568, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 219, 510, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 165, 448, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 213, 508, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 261, 634, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 312, 599, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 205, 493, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 134, 402, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 304, 601, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 260, 553, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 254, 176, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 255, 198, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 256, 538, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 217, 496, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 120, 411, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 208, 502, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 365, 626, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 305, 638, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 217, 506, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 215, 598, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 321, 643, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 367, 640, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 218, 594, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 179, 631, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 249, 604, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 267, 504, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 174, 638, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 205, 641, 0, 1);
        a.mousePressed(m);
        a.draw();

        //testing check function with invalid input
        assert a.check('a', a.board) == false;

        a.testing();
        a.setup();
        a.draw();
        a.key = 'a';
        a.keyPressed();
        a.draw();
        a.keyPressed();
        a.draw();
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 371, 599, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 353, 68, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 361, 160, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 358, 606, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 359, 484, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 405, 56, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 403, 150, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 326, 638, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 639, 321, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 307, 8, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 412, 63, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 666, 330, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 648, 74, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 397, 55, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 558, 216, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 657, 69, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 645, 20, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 596, 71, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 592, 124, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 642, 30, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 590, 25, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 557, 72, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 555, 121, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 593, 16, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 553, 18, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 511, 67, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 499, 160, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 550, 31, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 557, 118, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 545, 204, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 607, 147, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 567, 129, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 588, 149, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 471, 61, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 463, 162, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 597, 158, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 461, 16, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 499, 27, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 497, 58, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 462, 32, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 495, 64, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 398, 35, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 359, 125, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 493, 77, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 513, 174, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 358, 22, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 312, 18, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 493, 157, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 453, 150, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 327, 4, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 347, 11, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 459, 163, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 362, 111, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 364, 25, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 364, 25, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 272, 35, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 344, 70, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 356, 114, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 505, 109, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 356, 66, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 319, 169, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 503, 104, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 466, 122, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 371, 31, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 316, 13, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 442, 113, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 453, 29, 0, 1);
        a.mousePressed(m);
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 264, 67, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 255, 150, 0, 1);
        a.mousePressed(m);
        a.draw();
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        for(int i = 0; i < 10800; i++){
            a.draw();
        }
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 264, 67, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 255, 150, 0, 1);
        a.mousePressed(m);
        a.draw();
        for(int i = 0; i < 10800; i++){
            a.draw();
        }
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 264, 67, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 255, 150, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 300, 600, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 302, 515, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 309, 27, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 31, 305, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 303, 636, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 258, 540, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 30, 322, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 161, 463, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 258, 548, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 207, 499, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 169, 450, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 215, 496, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 275, 658, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 313, 598, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 220, 498, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 310, 499, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 308, 598, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 255, 504, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 317, 508, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 259, 500, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 163, 645, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 206, 542, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 253, 511, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 206, 552, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 402, 627, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 456, 553, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 215, 546, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 217, 597, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 273, 601, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 274, 517, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 220, 638, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 223, 606, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 218, 639, 0, 1);
        a.mousePressed(m);
        a.draw();
        a.key = 'e';
        a.keyPressed();
        a.draw();
        a.key = 'r';
        a.keyPressed();
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 264, 67, 0, 1);
        a.mousePressed(m);
        a.draw();
        m = new MouseEvent(null, 1, MouseEvent.CLICK, 0, 255, 150, 0, 1);
        a.mousePressed(m);
        a.draw();
        for(int i = 0; i < 10800; i++){
            a.draw();
        }
        a.key = 'r';
        a.keyPressed();
        a.draw();
        a.key = 'e';
        a.keyPressed();
        a.draw();
        
        assert a.checkmate('a') == false;
    }
}
